const constants = {
  FORM_INPUT: 'FORM_INPUT',
  FORM_SUBMIT: 'FORM_SUBMIT',
  TODO_ADD: 'TODO_ADD',
  TODO_TOGGLE: 'TODO_TOGGLE',
  TODO_DELETE: 'TODO_DELETE',
  TODO_START_EDITING: 'TODO_START_EDITING',
  TODO_DONE_EDITING: 'TODO_DONE_EDITING',
  TODO_CANCEL_EDITING: 'TODO_CANCEL_EDITING',

  FILTER_ALL: '',
  FILTER_PENDING: 'pending',
  FILTER_COMPLETED: 'completed',
};

export default constants;
